nikki = Lover.create(name: "Nikki", gender: "Female", personality: "Fierce", interest: "fitness", fitness_req: 30, intellect_req: 15, kindness_req: 15, money_req: 100,
  fact_place: "I love leg day",
  fact_color: "My favorite color is blue",
  fact_dream: "If I could, I'd live next to the ocean",
  fact_season: "Summer is my favorite season.",
  fact_food: "I could eat acai bowls everyday",
  fact_item: "Could you help me roll out my back??",
  aff_fitness_mod: 2,
  aff_intellect_mod: 1,
  aff_kindness_mod: 2,
  aff_money_mod: 10,
  aff_pts_req: 400,
  first_meeting: "Nikki: Oh, hi! You must be new here. My name is Nikki. Nice to meet you.")
kira = Lover.create(name: "Kira", gender: "Female", personality: "Sweet", interest: "volunteering", fitness_req: 10, intellect_req: 20, kindness_req: 30, money_req: 50,
  fact_color: "My favorite color is purple",
  fact_item: "I love animals!!",
  fact_dream: "It's my dream to save someone's life!!",
  fact_season: "I love the winter, so I can cuddle and drink hot cocoa",
  fact_food: "Oh... actually, I'm vegan",
  fact_place: "It's a lot of fun to go to the countryside.",
  aff_fitness_mod: 1,
  aff_intellect_mod: 2,
  aff_kindness_mod: 2,
  aff_money_mod: 20,
  aff_pts_req: 500,
  first_meeting: "Kira: Hello!! I'm Kira!! Sorry it's a mess in here...")
princess = Lover.create(name: "Princess", gender: "Female", personality: "Shallow", interest: "money", fitness_req: 30, intellect_req: 30, kindness_req: 10, money_req: 1000,
  fact_item: "I really want this Louis Vuitton purse!!",
  fact_dream:"I can't decide between an Audi or Mercedes for my next car.",
  fact_place:"Can I have some money to get my nails done?",
  fact_color: "Can you buy me this in pink??? Pleaaaasseeeeeee!",
  fact_season: "Ugh. I hate the winter. I can't wait for the summer",
  fact_food: "OMG. Take me to this fancy restaurant. It has four dollar signs on Yelp",
  aff_fitness_mod: 4,
  aff_intellect_mod: 1,
  aff_kindness_mod: 1,
  aff_money_mod: 50,
  aff_pts_req: 400,
  first_meeting: "Princess: Excuse me. You're literally standing in the middle of the hallway. Can you move?")
penelope = Lover.create(name: "Penelope", gender: "Female", personality: "Nerdy", interest: "intellect", fitness_req: 10, intellect_req: 40, kindness_req: 10, money_req: 20,
  fact_place: "I absolutely adore the library",
  fact_item: "My favorite author of ALL TIME is Edgar Allen Poe",
  fact_season: "Pumpkin spice lattes are my guilty pleasure",
  fact_color: "Black cats match my witch aesthetic",
  fact_food: "I could eat mac n cheese everyday",
  fact_dream: "I would die if I could meet Michelle Obama",
  aff_fitness_mod: 1,
  aff_intellect_mod: 3,
  aff_kindness_mod: 3,
  aff_money_mod: 10,
  aff_pts_req: 700,
  first_meeting: "Penelope: Welcome to the library. Do you need to sign up for a new card?")


ryan = Lover.create(name: "Ryan", gender: "Male", personality: "Quiet", interest: "intellect", fitness_req: 5, intellect_req: 30, kindness_req: 10, money_req: 20,
  fact_place: "I really love coffee shops...",
  fact_item: "My mom handmade this scarf for me. It's a little beat up, but I love it",
  fact_season: "Fall is the best season for reading a book.",
  fact_color: "It's easier to buy all black",
  fact_food: "I make a mean spaghetti bolognese",
  fact_dream: "I've always wanted to travel to Norway",
  aff_fitness_mod: 4,
  aff_intellect_mod: 1,
  aff_kindness_mod: 1,
  aff_money_mod: 10,
  aff_pts_req: 400,
  first_meeting: "Ryan: ...")
john = Lover.create(name: "John", gender: "Male", personality: "Funny", interest: "money", fitness_req: 15, intellect_req: 10, kindness_req: 10, money_req: 1000,
  fact_place: "I like to go to the Equinox on Wall St",
  fact_item: "Can you be careful not to scratch my jacket? It's real leather",
  fact_season: "Winter is the best season for men's fashion",
  fact_color: "Do you think charcoal gray looks better? Or do you like the midnight blue on me?",
  fact_food: "I love sushi",
  fact_dream: "Ooooh, that Lamborghini is sweet",
  aff_fitness_mod: 1,
  aff_intellect_mod: 1,
  aff_kindness_mod: 1,
  aff_money_mod: 25,
  aff_pts_req: 600,
  first_meeting: "John: Hey there. Welcome to hell.")
fabio = Lover.create(name: "Fabio", gender: "Male", personality: "Strong", interest: "fitness", fitness_req: 30, intellect_req: 5, kindness_req: 5, money_req: 50,
  fact_place: "My home country, Italia, is a gorgeous place",
  fact_item: "All I need in life is my Maserati",
  fact_season: "I wish it could be eternal summer, like my heart",
  fact_color: "Red is a beautiful color. A color of passion",
  fact_food: "Oysters, cheese, and wine. I enjoy aphrodisiacs",
  fact_dream: "I would love to build my own cabin in the mountains",
  aff_fitness_mod: 3,
  aff_intellect_mod: 1,
  aff_kindness_mod: 1,
  aff_money_mod: 50,
  aff_pts_req: 600,
  first_meeting: "Fabio: *grunts*")
oliver = Lover.create(name: "Oliver", gender: "Male", personality: "Sweet", interest: "volunteering", fitness_req: 0, intellect_req: 15, kindness_req: 25, money_req: 10,
  fact_place: "I know this sounds cheesy, but I love volunteering at the shelter",
  fact_item: "Don't laugh but I actually have a vegetable garden",
  fact_season: "Spring is the best season for plants!!",
  fact_color: "I like the color green and brown",
  fact_food: "I love all types of food!!",
  fact_dream: "I would like to retire on a farm someday",
  aff_fitness_mod: 1,
  aff_intellect_mod: 1,
  aff_kindness_mod: 1,
  aff_money_mod: 10,
  aff_pts_req: 500,
  first_meeting: "Oliver: Hi newbie. Welcome!!")
